# 
# Hello World!
#
#	a simple picoVersat program
#

# uncomment test ADD instruction        
#        ldi 2
#        wrw R1
#        ldi 3
#        wrw R2
#        add R1
#        wrw TRAP_BASE

#   assign regC = {negative, overflow, {(`DATA_W-3){1'b0}}, carry};

#uncomment to test carry and negative
        ldi 1
        wrw R0
        ldi -1
        addi -1
        addi 4
        
#uncomment to test overflow
        ldi 0xffff
        ldi 0x7fff
        wrw R1
        ldi 0
        add R1
        add R1

# set R1 iterator 	
	ldi 15
	wrw R1
	
# set RB to point to first char
        ldi c0
        wrw R4
	wrw RB

# read string from memory and write to char printer 
loop 	rdwb
	rdwb            #need to read twice due to memory 1 cycle delay
	wrw CPRT_BASE
	rdw RB          #load pointer
	addi 1	        #increment by 1
	wrw RB          #store incremented pointer
	rdw R1          #load iterator
	bneqi loop      #go back to loop if non-zero, regA is decremented
	wrw R1          #stores back decremented iterator


#finish by activating trap
end	wrw TRAP
        
# char ascii constants placed here	
c0	.memset 0x0A
	.memset 0x48
	.memset 0x65
	.memset 0x6C
	.memset 0x6C
	.memset 0x6F
	.memset 0x20
	.memset 0x77
	.memset 0x6F
	.memset 0x72
	.memset 0x6C
	.memset 0x64
	.memset 0x21
	.memset 0x0A
	.memset 0x0D
	.memset 0x0A
